name: Release

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          show-progress: true,

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build all plugins
        run: |
          dotnet restore
          dotnet build --no-restore

      - name: Publish plugins
        run: |
          dotnet publish src/Jailbreak.Core/Jailbreak.Core.csproj --no-build --no-restore -o build/Jailbreak.Core
          dotnet publish src/Jailbreak.LastRequest/Jailbreak.LastRequest.csproj --no-build --no-restore -o build/Jailbreak.LastRequest
          dotnet publish src/Jailbreak.Fun/Jailbreak.Fun.csproj --no-build --no-restore -o build/Jailbreak.Fun
          dotnet publish src/Jailbreak.Zones/Jailbreak.Zones.csproj --no-build --no-restore -o build/Jailbreak.Zones
          dotnet publish src/Jailbreak.Gangs/Jailbreak.Gangs.csproj --no-build --no-restore -o build/Jailbreak.Gangs
          dotnet publish src/Jailbreak.Tools/Jailbreak.Tools.csproj --no-build --no-restore -o build/Jailbreak.Tools
          dotnet publish src/Jailbreak.Updater/Jailbreak.Updater.csproj --no-build --no-restore -o build/Jailbreak.Updater

      - uses: actions/upload-artifact@v4.0.0
        with:
          name: jailbreak
          path: build/
          if-no-files-found: error

      - name: Create release zip
        run: |
          cd build && zip -r ../Jailbreak.zip . && cd ..

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          fail_on_unmatched_files: true
          files: Jailbreak.zip
          body_path: .github/release_template.md
